M48
; DRILL file {KiCad 9.0.7} date 2026-02-24T19:07:47+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-24T19:07:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.000
%
G90
G05
T1
X25.45Y50.625
T2
X15.55Y48.7
X15.55Y41.7
T3
X45.45Y50.625
T4
X49.1Y51.75
X49.1Y3.75
T5
X49.1Y51.75
X49.1Y3.75
M30
